apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nhaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nhaz
    app.kubernetes.io/part-of: city-of-dc
  name: dc-metro-map-nhaz
  namespace: shbose-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-nhaz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-nhaz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:85ec7e265b73cbe2a9ff027e10a88dfad3eeedabfff69c6159cf7289b2b9ee95
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
