apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nhaz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nhaz
    app.kubernetes.io/part-of: city-of-dc
  name: dc-metro-map-nhaz
  namespace: shbose-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: dc-metro-map-nhaz
status:
  loadBalancer: {}
